# Generated by Django 2.2.1 on 2019-05-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('ns_category_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('job_type_id', models.IntegerField()),
                ('job_type', models.IntegerField()),
                ('_id', models.IntegerField()),
                ('filename', models.TextField()),
                ('job_title', models.TextField()),
                ('job_slug', models.TextField()),
                ('job_description', models.TextField()),
                ('job_image', models.TextField()),
                ('job_status', models.TextField()),
                ('location', models.CharField(max_length=60)),
                ('House_of', models.CharField(max_length=60)),
                ('Year', models.DateTimeField()),
                ('epaper_link', models.URLField()),
                ('image_link', models.URLField()),
            ],
        ),
    ]
