# Generated by Django 2.2.1 on 2019-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190524_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='House_of',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='epaper_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='filename',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='job_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='job_slug',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='job_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='job_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='job_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='job_type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='ns_category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
